### ISSUE TITLE
[Enhancement] MaterialKit causing leak

### ISSUE THREAD

**Issue by ApolloZhu** [LiulietLee/Pick-Color#2]
![MKTextField Leaking](https://cloud.githubusercontent.com/assets/10842684/19703440/d77df2f4-9ad1-11e6-9531-2ddd1271d40c.png)
Currently trying to fix this
Tried to add `weak` to these [properties](https://github.com/LiulietLee/Pick-Color/blob/master/Pick%20Color/MKLayer.swift#L44-L45), does solve the problem, but causing the entire app to crash due to unknown reason

**Comment by LiulietLee** [comment]
Alright, I see. If we can't solve it, I will remove materialkit.

**Comment by LiulietLee** [comment]
Good job!
